# Generated by Django 4.2.3 on 2023-07-18 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Proyecto',
            new_name='Bicicleta',
        ),
    ]
