# Generated by Django 4.2.3 on 2023-07-18 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_remove_bicicleta_precio_usd_alter_bicicleta_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bicicleta',
            name='precio',
            field=models.TextField(max_length=50),
        ),
    ]
