# Generated by Django 4.2.3 on 2023-07-18 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_alter_bicicleta_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bicicleta',
            name='precio',
            field=models.CharField(max_length=30),
        ),
    ]
