# Generated by Django 4.2.3 on 2023-07-18 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_alter_bicicleta_precio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bicicleta',
            options={'ordering': ['-creado'], 'verbose_name': 'Bicicletas', 'verbose_name_plural': 'Bicicletas'},
        ),
        migrations.AlterField(
            model_name='bicicleta',
            name='imagen',
            field=models.ImageField(upload_to='Bicicletas'),
        ),
    ]
